// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArSX1BjOZqMu5BC9iX3VBC-QxMTIVHQbo',
    appId: '1:845205637188:web:4760201ece408b23e01411',
    messagingSenderId: '845205637188',
    projectId: 'handee-app-3fcaf',
    authDomain: 'handee-app-3fcaf.firebaseapp.com',
    storageBucket: 'handee-app-3fcaf.firebasestorage.app',
    measurementId: 'G-68T7NWQM07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzU6M3Y3HDXfks8zOE7F7GNagZGp4FNcw',
    appId: '1:845205637188:android:971365580fe72ef3e01411',
    messagingSenderId: '845205637188',
    projectId: 'handee-app-3fcaf',
    storageBucket: 'handee-app-3fcaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRtuP02YaSOGcenQoSpewVHwZYXYwDeLE',
    appId: '1:845205637188:ios:b185a9fdde496737e01411',
    messagingSenderId: '845205637188',
    projectId: 'handee-app-3fcaf',
    storageBucket: 'handee-app-3fcaf.firebasestorage.app',
    iosBundleId: 'com.example.handee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRtuP02YaSOGcenQoSpewVHwZYXYwDeLE',
    appId: '1:845205637188:ios:b185a9fdde496737e01411',
    messagingSenderId: '845205637188',
    projectId: 'handee-app-3fcaf',
    storageBucket: 'handee-app-3fcaf.firebasestorage.app',
    iosBundleId: 'com.example.handee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArSX1BjOZqMu5BC9iX3VBC-QxMTIVHQbo',
    appId: '1:845205637188:web:0db180eae70f60dfe01411',
    messagingSenderId: '845205637188',
    projectId: 'handee-app-3fcaf',
    authDomain: 'handee-app-3fcaf.firebaseapp.com',
    storageBucket: 'handee-app-3fcaf.firebasestorage.app',
    measurementId: 'G-T5TJEKBYXC',
  );
}
